### PR TITLE
feat: add cmux to listen many protocols on same port

### LINKED ISSUE #147: Add protocol multiplexer
Exploring the benefits of using a multiplexing library of network connections such a [cmux](https://github.com/soheilhy/cmux), allowing Pop to serve different protocols (HTTP / RPC / TCP / ...) on the same listener.

### PR DESCRIPTION
**Pull request by gallexis**
closes #147

### CODE REVIEW

**Comment by gallexis** [comment]
It currently serves pop queries a http requests, but haven't tried it yet on rpc

**Comment by gallexis** [comment]
> It currently serves pop queries and http requests, but haven't tried it yet on rpc

Should be working fine with RPC now

**Review by tchardin — COMMENTED** [review]
Should we remove `node/socket.go`? Shouldn't be needed anymore no?

**Comment by gallexis** [comment]
> Should we remove `node/socket.go`? Shouldn't be needed anymore no?

Yes indeed, will update that

**Review by tchardin — APPROVED** [review]
This is great. Thanks!

**Pull request merged**
